// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzljlujhlqfvndrvlohy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bGpsdWpobHFmdm5kcnZsb2h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTE0NzcsImV4cCI6MjA2NTM4NzQ3N30.4EfGlmC9ogIxA_g7GTt1cYj8kalgbdKgQbiS4_u5lTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);